name: kv release

on:
  push:
    paths:
      - 'kv/**'
      - '.github/workflows/kv.yml'
    tags: [ 'kv/*' ]
    branches:
      - '*'
jobs:
  test:
    name: test kv with released dependencies
    runs-on: ubuntu-latest-4-cores
    environment: CI
    strategy:
      matrix:
        deno-version: [1.45.x]

    steps:
      - name: Git Checkout Kv
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install nats-server
        uses: aricart/install-binary@v1.0.0
        with:
          repo: nats-io/nats-server
          name: nats-server
          cache: true

      - name: Lint Deno Module
        working-directory: kv
        run: |
          deno fmt --check
          deno lint
      - name: Test Deno Module
        working-directory: kv
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
          NGS_CI_USER: ${{ secrets.NGS_CI_USER }}
        run: |
          deno task test

      - name: Build NPM core bundle
        working-directory: kv
        env:
          CI: true
        run: |
          npm install
          npm run prepack
          npm link

      - name: Test Node Transport with local kv
        working-directory: transport-node
        env:
          CI: true
        run: |
          npm install
          npm run prepack
          npm link @nats-io/kv
          npm test
