name: services release

on:
  push:
    paths:
      - 'services/**'
    tags: [ 'services/*' ]
    branches:
      - '*'
jobs:
  test:
    name: test services with released dependencies
    runs-on: ubuntu-latest-4-cores
    environment: CI
    strategy:
      matrix:
        deno-version: [1.x.x]

    steps:
      - name: Git Checkout Services
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install nats-server
        uses: aricart/install-binary@v1.0.0
        with:
          repo: nats-io/nats-server
          name: nats-server
          cache: true

      - name: Set NATS Server Version
        run: echo "NATS_VERSION=v2.10.17" >> $GITHUB_ENV

      - name: Get nats-server
        run: |
          wget "https://github.com/nats-io/nats-server/releases/download/$NATS_VERSION/nats-server-$NATS_VERSION-linux-amd64.zip" -O tmp.zip
          unzip tmp.zip
          mv nats-server-$NATS_VERSION-linux-amd64 nats-server
          rm nats-server/README.md LICENSE

      - name: Lint Deno Module
        working-directory: services
        run: |
          deno fmt --check
          deno lint
      - name: Test Deno Module
        working-directory: services
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
          NGS_CI_USER: ${{ secrets.NGS_CI_USER }}
        run: |
          deno task test


